# nginx-anotations.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    author: Michael Faraday
    e-mail: michael@faraday.com
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never
