# rebalance-up.yaml
# Scale key/store cluster to 3 replicas from 2
apiVersion: v1
kind: Pod 
metadata:
  name: rebalance 
spec:
  restartPolicy: Never
  containers:
  - name: rebalance
    image: python:alpine
    args:
    - bin/sh
    - -c
    - > 
      python -u /var/scripts/rebalance.py
      server-0.server,server-1.server
      server-0.server,server-1.server,server-2.server
    volumeMounts:
      - name: scripts 
        mountPath: /var/scripts
  volumes: 
  - name: scripts 
    configMap: 
      name: scripts 